# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
np.__version__

'1.23.5'

2) Создать нулевой вектор размера 10

In [2]:
import numpy as np

vec = np.zeros(10)

print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [3]:
import numpy as np

vec = np.zeros(7)

for i in range(len(vec)):
    vec[i] = 7

print(vec)

[7. 7. 7. 7. 7. 7. 7.]


4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
import numpy as np

arr = []

for i in range(10,100):
    if i%2 ==0:
        arr.append(i)

vec = np.array(arr)

print(vec)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
import numpy as np

arr = np.random.random_sample(10)

print(arr, '\n')

reversed_arr = np.flipud(arr)

print(reversed_arr)

[0.87074122 0.27053773 0.94945588 0.05374751 0.76285934 0.97918879
 0.05606448 0.20527101 0.04366039 0.80288059] 

[0.80288059 0.04366039 0.20527101 0.05606448 0.97918879 0.76285934
 0.05374751 0.94945588 0.27053773 0.87074122]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [6]:
import numpy as np

arr = np.arange(9).reshape(3,3)

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [7]:
import numpy as np

vec = np.eye(4,4,1)

print(vec)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:
import numpy as np

arr = np.full((4, 4), 7)

for i in range(0,len(arr)):
    arr[i][i] = i+1

print(arr)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
import numpy as np

arr = np.zeros((5,5))

for i in range(0,len(arr)):
    j = 0
    while j < len(arr):
        arr[i][j] = i
        j +=1

print(arr)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
import numpy as np

arr = np.random.randint(0, 9, (10, 10)) # от 0 до 9, размера (10 на 10)
aver_column = np.mean(arr,axis=1)

print(arr, '\n'*2, aver_column, '\n'*2)

for i in range(0,len(arr)):
    for j in range(0,len(arr)):
        arr[i][j] -= aver_column[i]

print(arr)

[[8 1 1 0 0 3 0 0 6 4]
 [2 1 5 0 4 7 5 3 5 3]
 [3 5 4 4 4 7 7 7 8 8]
 [5 0 5 6 1 4 7 0 1 0]
 [0 5 6 0 8 7 5 2 2 2]
 [2 4 8 7 1 7 0 7 7 3]
 [1 1 7 4 4 8 1 0 4 4]
 [5 6 1 2 1 4 8 3 1 0]
 [8 4 2 0 2 0 2 3 3 7]
 [0 5 8 5 5 1 1 1 4 1]] 

 [2.3 3.5 5.7 2.9 3.7 4.6 3.4 3.1 3.1 3.1] 


[[ 5 -1 -1 -2 -2  0 -2 -2  3  1]
 [-1 -2  1 -3  0  3  1  0  1  0]
 [-2  0 -1 -1 -1  1  1  1  2  2]
 [ 2 -2  2  3 -1  1  4 -2 -1 -2]
 [-3  1  2 -3  4  3  1 -1 -1 -1]
 [-2  0  3  2 -3  2 -4  2  2 -1]
 [-2 -2  3  0  0  4 -2 -3  0  0]
 [ 1  2 -2 -1 -2  0  4  0 -2 -3]
 [ 4  0 -1 -3 -1 -3 -1  0  0  3]
 [-3  1  4  1  1 -2 -2 -2  0 -2]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
import numpy as np

arr = np.random.randint(0, 10, (10, 10)) # случайные от 0 до 10, размера (10 на 10)

print(arr,'\n'*2)

for i in range(0,len(arr)):
    center_row = (max(arr[i]) + min(arr[i]))/2
    for j in range(0,len(arr)):
        arr[i][j] -= center_row

print(arr)

[[9 8 0 7 7 4 0 4 5 7]
 [9 0 8 0 9 7 0 0 5 5]
 [3 7 3 8 7 7 8 6 4 3]
 [2 0 6 1 2 8 1 2 1 8]
 [0 8 1 6 7 0 2 2 3 8]
 [3 7 8 4 0 1 2 6 8 2]
 [8 7 7 3 7 4 0 3 8 3]
 [7 4 7 9 8 2 0 0 9 6]
 [9 0 7 3 7 3 7 9 9 6]
 [3 4 8 8 1 9 2 7 1 4]] 


[[ 4  3 -4  2  2  0 -4  0  0  2]
 [ 4 -4  3 -4  4  2 -4 -4  0  0]
 [-2  1 -2  2  1  1  2  0 -1 -2]
 [-2 -4  2 -3 -2  4 -3 -2 -3  4]
 [-4  4 -3  2  3 -4 -2 -2 -1  4]
 [-1  3  4  0 -4 -3 -2  2  4 -2]
 [ 4  3  3 -1  3  0 -4 -1  4 -1]
 [ 2  0  2  4  3 -2 -4 -4  4  1]
 [ 4 -4  2 -1  2 -1  2  4  4  1]
 [-2 -1  3  3 -4  4 -3  2 -4 -1]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
import numpy as np

arr = np.random.randint(0, 10, (5, 5)) # случайные от 0 до 10, размера (10 на 10)
max_min = []

print(arr,'\n'*2)

for i in range(0,len(arr)):
    max_min.append([max(arr[i]), min(arr[i])])

arr = np.hstack((arr,max_min))
print(arr)

[[1 8 7 9 1]
 [4 8 7 5 6]
 [6 5 2 9 1]
 [4 7 0 1 1]
 [5 8 3 9 3]] 


[[1 8 7 9 1 9 1]
 [4 8 7 5 6 8 4]
 [6 5 2 9 1 9 1]
 [4 7 0 1 1 7 0]
 [5 8 3 9 3 9 3]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
import numpy as np

arr = np.arange(1,51)

arr_even = []
arr_not_even = []

for i in range(0,len(arr)):
    if arr[i]%2==0:
        arr_even.append(arr[i])
    else:
        arr_not_even.append(arr[i])

arr_even = np.array(arr_even)
arr_even = arr_even.reshape(5,5)

arr_not_even = np.array(arr_not_even)
arr_not_even = arr_not_even.reshape(5,5)

print(arr_even, '\n'*2)
print(arr_not_even, '\n'*2)

composition = np.dot(arr_even, arr_not_even)
composition = np.array(composition)

print(composition, '\n'*2)

inverse_arr = np.linalg.pinv(composition)

print(inverse_arr)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]] 


[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]] 


[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]] 


[[ 1.012e-02  6.410e-03  2.700e-03 -1.010e-03 -4.720e-03]
 [ 5.420e-03  3.435e-03  1.450e-03 -5.350e-04 -2.520e-03]
 [ 7.200e-04  4.600e-04  2.000e-04 -6.000e-05 -3.200e-04]
 [-3.980e-03 -2.515e-03 -1.050e-03  4.150e-04  1.880e-03]
 [-8.680e-03 -5.490e-03 -2.300e-03  8.900e-04  4.080e-03]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
import numpy as np

arr = np.zeros((5,5))

for i in range(0,len(arr)):
    for j in range(0,len(arr)):
        if i%2==0 and j%2!=0:
            arr[i][j] = 1
        elif i%2!=0 and j%2==0:
            arr[i][j] = 1

print(arr)

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]
